INSERT OR REPLACE INTO News (id, title, slug, category, date, excerpt, content, image, status, featured, createdAt, updatedAt) VALUES
('news-001', 'Penguatan Pembelajaran Berbasis Proyek di Lingkungan Jurusan', 'penguatan-pembelajaran-berbasis-proyek', 'Akademik', '2026-08-12T00:00:00.000Z', 'Berita placeholder tentang pengembangan proses pembelajaran yang menekankan praktik, kolaborasi, dan evaluasi berbasis karya.', 'Konten berita ini merupakan placeholder formal yang dapat diganti dengan informasi resmi jurusan setelah proses editorial selesai.', NULL, 'published', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('news-002', 'Mahasiswa Mengikuti Kegiatan Pengembangan Kompetensi Digital', 'pengembangan-kompetensi-digital-mahasiswa', 'Kemahasiswaan', '2026-08-18T00:00:00.000Z', 'Informasi dummy mengenai aktivitas mahasiswa dalam memperkuat kemampuan teknologi, komunikasi, dan kerja tim.', 'Konten placeholder ini disiapkan sebagai contoh berita kemahasiswaan yang dapat dikelola melalui CMS sederhana.', NULL, 'published', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('news-003', 'Riset Terapan Informatika untuk Solusi Digital Masyarakat', 'riset-terapan-informatika-solusi-digital', 'Penelitian', '2026-08-24T00:00:00.000Z', 'Berita placeholder tentang arah penelitian terapan yang berfokus pada kebutuhan akademik, organisasi, dan masyarakat.', 'Isi berita riset ini masih berupa data dummy dan tidak memuat klaim atau nama pihak tertentu.', NULL, 'published', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('news-004', 'Inisiasi Kerja Sama Pembelajaran dan Literasi Teknologi', 'inisiasi-kerja-sama-literasi-teknologi', 'Kerja Sama', '2026-09-02T00:00:00.000Z', 'Informasi dummy tentang peluang kolaborasi untuk mendukung kegiatan akademik, pelatihan, dan pengembangan kompetensi.', 'Konten kerja sama ini disiapkan agar struktur CMS dapat diuji tanpa memakai nama mitra resmi.', NULL, 'published', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('news-005', 'Pengumuman Layanan Administrasi Akademik Semester Berjalan', 'pengumuman-layanan-administrasi-akademik', 'Pengumuman', '2026-09-08T00:00:00.000Z', 'Pengumuman placeholder mengenai layanan akademik, jadwal koordinasi, dan informasi umum yang dapat diperbarui.', 'Isi pengumuman ini merupakan contoh untuk kebutuhan pengujian halaman daftar dan detail berita.', NULL, 'draft', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('news-006', 'Dokumentasi Kegiatan Pengabdian Berbasis Literasi Digital', 'dokumentasi-pengabdian-literasi-digital', 'Kemahasiswaan', '2026-09-15T00:00:00.000Z', 'Berita dummy mengenai kegiatan pengabdian yang melibatkan mahasiswa dalam edukasi teknologi secara bertanggung jawab.', 'Konten pengabdian ini masih placeholder dan dapat diperluas menjadi berita lengkap setelah data resmi tersedia.', NULL, 'published', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT OR REPLACE INTO Agenda (id, title, slug, category, date, time, location, statusAgenda, excerpt, content, image, publishStatus, featured, createdAt, updatedAt) VALUES
('agenda-001', 'Seminar Etika dan Karier Teknologi Informasi', 'seminar-etika-karier-teknologi-informasi', 'Seminar', '2026-09-20T00:00:00.000Z', '09.00 - 11.30 WITA', 'Kampus', 'upcoming', 'Agenda placeholder untuk membahas kesiapan akademik, etika profesi, dan arah pengembangan karier bidang informatika.', 'Konten agenda ini masih berupa placeholder dan dapat diperbarui dengan informasi resmi.', NULL, 'published', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('agenda-002', 'Workshop Dasar Analisis Data untuk Mahasiswa', 'workshop-dasar-analisis-data', 'Workshop', '2026-09-25T00:00:00.000Z', '13.00 - 16.00 WITA', 'Laboratorium', 'upcoming', 'Kegiatan dummy berupa pelatihan pengolahan data, visualisasi, dan penyajian hasil analisis sederhana.', 'Deskripsi lengkap agenda ini dapat diganti dengan rundown atau informasi resmi ketika tersedia.', NULL, 'published', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('agenda-003', 'Kuliah Tamu Transformasi Digital dan Inovasi', 'kuliah-tamu-transformasi-digital', 'Kuliah Tamu', '2026-09-30T00:00:00.000Z', '10.00 - 12.00 WITA', 'Hybrid', 'upcoming', 'Agenda placeholder untuk memperkaya wawasan mahasiswa mengenai perkembangan transformasi digital.', 'Konten kuliah tamu ini merupakan data dummy tanpa nama narasumber asli.', NULL, 'published', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('agenda-004', 'Rapat Akademik Evaluasi Pembelajaran', 'rapat-akademik-evaluasi-pembelajaran', 'Rapat Akademik', '2026-10-05T00:00:00.000Z', '09.00 - 10.30 WITA', 'Kampus', 'ongoing', 'Agenda dummy untuk koordinasi evaluasi pembelajaran dan penguatan layanan akademik jurusan.', 'Konten rapat akademik ini dapat diganti dengan catatan agenda internal yang sesuai.', NULL, 'draft', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('agenda-005', 'Kegiatan Mahasiswa Pengembangan Produk Digital', 'kegiatan-mahasiswa-produk-digital', 'Kegiatan Mahasiswa', '2026-10-12T00:00:00.000Z', '08.30 - 15.00 WITA', 'Online', 'completed', 'Agenda placeholder untuk ruang kolaborasi mahasiswa dalam menyusun gagasan produk dan prototipe digital.', 'Konten agenda mahasiswa ini masih placeholder dan mudah diganti lewat admin.', NULL, 'published', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT OR REPLACE INTO StudentAchievement (id, title, slug, studentName, level, eventName, organizer, date, description, image, attachment, publicationStatus, createdAt, updatedAt) VALUES
('achievement-001', 'Juara Lomba Pengembangan Aplikasi Edukasi', 'juara-lomba-pengembangan-aplikasi-edukasi', 'Tim Informatika UHN', 'national', 'Kompetisi Inovasi Digital Mahasiswa', 'Panitia Kompetisi Nasional', '2026-06-12T00:00:00.000Z', 'Mahasiswa mengembangkan prototipe aplikasi edukasi berbasis kebutuhan pembelajaran digital. Data ini contoh awal dan dapat diganti melalui CMS.', NULL, NULL, 'published', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('achievement-002', 'Finalis Ide Bisnis Teknologi Berkelanjutan', 'finalis-ide-bisnis-teknologi-berkelanjutan', 'Kelompok Wirausaha Digital', 'regional', 'Innovation Pitching Day', 'Komunitas Startup Pendidikan', '2026-07-08T00:00:00.000Z', 'Tim mahasiswa menyusun gagasan layanan digital yang mendukung literasi teknologi dan dampak sosial.', NULL, NULL, 'published', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('achievement-003', 'Penghargaan Karya Tulis Ilmiah Mahasiswa', 'penghargaan-karya-tulis-ilmiah-mahasiswa', 'Mahasiswa Informatika', 'local', 'Pekan Kreativitas Akademik', 'Jurusan Informatika', '2026-08-03T00:00:00.000Z', 'Prestasi placeholder untuk menguji alur draft dan publikasi pada CMS kemahasiswaan.', NULL, NULL, 'draft', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT OR REPLACE INTO StudentActivity (id, title, slug, category, date, location, description, image, attachment, publicationStatus, createdAt, updatedAt) VALUES
('activity-001', 'Workshop Pengembangan Web untuk Mahasiswa Baru', 'workshop-pengembangan-web-mahasiswa-baru', 'Workshop', '2026-06-20T00:00:00.000Z', 'Laboratorium Informatika', 'Kegiatan pengenalan pengembangan web, pengelolaan proyek, dan praktik kolaborasi teknis bagi mahasiswa.', NULL, NULL, 'published', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('activity-002', 'Seminar Etika Digital dan Keamanan Data', 'seminar-etika-digital-keamanan-data', 'Seminar', '2026-07-15T00:00:00.000Z', 'Aula Kampus', 'Seminar membahas perilaku digital bertanggung jawab, privasi, dan keamanan data dalam aktivitas akademik.', NULL, NULL, 'published', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('activity-003', 'Rapat Koordinasi Himpunan Mahasiswa Informatika', 'rapat-koordinasi-himpunan-mahasiswa-informatika', 'Organisasi', '2026-08-18T00:00:00.000Z', 'Ruang Jurusan', 'Kegiatan internal placeholder untuk menguji pengelolaan data draft kegiatan mahasiswa.', NULL, NULL, 'draft', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT OR REPLACE INTO ActivityGalleryImage (id, activityId, url, alt, sortOrder, createdAt) VALUES
('gallery-001', 'activity-001', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3', 'Dokumentasi workshop mahasiswa', 1, CURRENT_TIMESTAMP),
('gallery-002', 'activity-002', 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4', 'Dokumentasi seminar mahasiswa', 1, CURRENT_TIMESTAMP);
